### ISSUE TITLE
Updates location

### ISSUE THREAD

**Issue by blackearth2014** [countmodula/VCVRackPlugins#10]
Where do you have the latest version before v1.0 location?

**Comment by AdamVerspaget** [comment]
Master is currently at 0.6.3

**Comment by Petervos2018** [comment]
Do you think/know if version 0.6.3 will ever be available in the Plugin library ?
Because as it is now I've downloaded/installed the 0.6.2 win.zip from the release hub and of course I'm getting an update red dot in Rack because it wants to downgrade your plugin to version 0.6.1.
Oh, and why is there no 0.6.3 version for windows ?

Greetings Peter.
