### ISSUE TITLE
event arranger doesn't output triggers/pulses

### ISSUE THREAD

**Issue by smok-e** [countmodula/VCVRackPlugins#21]
I tried the event arragnger, but somehow it doesn't output any triggers,
only the 50/50 pulse gives out constant 10V
although the lights of the setps turn on and off.

maybe I'm doing something wrong?
I connected a Clocked from Impromptu to the clock input and set it to run.
but no output signals :(

**Comment by AdamVerspaget** [comment]
Hi, can you please attach a screen capture of your patch or possibly event the patch file for me to look at?

Do you have the Run output of Clocked connected to the Run input on the Event Arranger? If so, this will inhibit the EA as Clocked outputs start/stop pulses whereas the EA expects a constant high gate.

**Comment by smok-e** [comment]
I understood that the run input needs a constant high gate,
I attach patch that does have no output of the arranger,
it had some output for the first seconds, but as soon as I changed the steps from x to 1 or 0 
it stoped the output.
and it doesn't matter which clk out of the clocked module I connect to the arranger.
 
[Count_Arranger_bug_1.zip](https://github.com/countmodula/VCVRackPlugins/files/3365460/Count_Arranger_bug_1.zip)

**Comment by AdamVerspaget** [comment]
OK cool. I only suggested the run thing as number of other people have been caught out by that on other modules so started with the obvious thing first. 

I have loaded up your patch and can see that you have bits 9, 7, 3 and 1 set. With theses settings, you will only get pulses whenever bit 9 is high AND bit 7 is high AND bit 3 is high AND bit 1 is high. Since this is a binary divider, bit 9 will only change states every 512 clock pulses, bit 7 after 128 clock pulses, bit 3 after 8 clock pulses and bit 1 every other clock pulse. When combined this reduces the frequency of output considerably. I think you are actually getting output pulses but the time between the them is longer than you are expecting.  To see this in action, you can connect the clock input of the EA to a faster clock (the CLK1 output and set it to something like x6 as I have shown below will do it) and you should see regular bursts of pulses with a period of inactivity between the bursts.

![EventArranger](https://user-images.githubusercontent.com/49931541/60767220-1e2b5280-a0f8-11e9-9967-da8cc547933c.png)

This is very much an experimental module designed to produce triggers in various patterns over time rather than standard clock divisions.

**Comment by smok-e** [comment]
Hi Adam, thank you very much for the detailed explanation
of how the module works,
I'm sorry but I didn't get it from the manual ;-)

So I tried it again and now I even got something that is a kind of musical 
I attach a patch you can try. 

But the arranger really needs a very fast clock to work with higher values.
I didn't go further then the 6 ( with a fast clock imho), but it still is slow.

anyway this can be also nice for sparse and more ambient patches, or when you try a patch like a song, where a voice triggered bythe Arranger plays only at certain times.

I like your modules and start to use them more and more in my patches.
and if you like you can try my now "unbugged" patch ;-)
[Count_Arranger_un-bugged_1.zip](https://github.com/countmodula/VCVRackPlugins/files/3365732/Count_Arranger_un-bugged_1.zip)

**Comment by AdamVerspaget** [comment]
Glad I could help out and there is no need to be sorry. I will try to amend the manual to make the module operation a bit clearer. I generally put the bare minimum into the manuals to encourage experimentation however that does sometimes end up with misunderstandings how a module works.
