### ISSUE TITLE
Burst Gen: EOC->Trigger triggers new burst early when running from internal clock

### ISSUE THREAD

**Issue by gbrinkert** [countmodula/VCVRackPlugins#26]
When running Burst Generator on the internal clock and patching the END out into the TRIG in (to create a constantly looping series of bursts), the module doesn't loop in time.  Instead, the amount of space between the last pulse and the first pulse of the next loop appears to be shortened.

This issue is not present when running from an external clock source.

**Comment by AdamVerspaget** [comment]
Interesting! If anything I would have thought external clock would have been an issue. I'll pop ti in the queue to be looked at.

**Comment by AdamVerspaget** [comment]
OK, I've just worked out what is going here. The module is functioning exactly as intended. The internal clock is reset when a trigger is detected so that the bursts start straight away rather than waiting for the next leading clock edge. When the duration ends, it ends at the negative edge of the last pulse, not the next positive clock pulse after that. What you are seeing is the last pulse of one duration butting up against the first pulse of the next. The reason it doesn't happen for an external clock is that the external clock is not reset so the bursts start where you are expecting them to start.
