### ISSUE TITLE
Binary Sequencer on Mac only sends Gates/Pulses but no out or inverse out (scope confirms)

### ISSUE THREAD

**Issue by fractalgee** [countmodula/VCVRackPlugins#4]
I have tried absolutely everything to get the Binary Sequencer to spit out CV via the Out and Inverse outputs at bottom. I can only see anything output on the Gate and Trigger outs if I plug in a Clock signal at top, but no matter what, no CV out at all.... Scope confirms that both outs at bottom are silent, outputting a steady 0V (i.e. nada). This is VCV Rack 0.6.2c on MacOS X 10.11.6

**Comment by AdamVerspaget** [comment]
Sorry to hear that. You haven't got anything plugged in the Run/Reset input have you? The sequencer will only output CV if there is nothing plugged into that input or if the signal presented to that high (> 0.1 v). Can you give me a screen sot of the patch?

**Comment by fractalgee** [comment]
[BinarySeqBug.vcv.zip](https://github.com/countmodula/VCVRackPlugins/files/3262501/BinarySeqBug.vcv.zip)

simplest patch possible. the gate and pulse outs are fine, no CV despite nada plugged into Rest/Run....

**Comment by AdamVerspaget** [comment]
Thanks for the patch file. Just loaded it up on to my windows machine (I have no mac to test it on) and it does look like nothing is happening on the scope however I think the CV output is too small for you to see. If you increase the scale of the scope you should see some action. You have the 2 volt scale selected which means you will only get very small voltages out with those knob settings. The 2 volt level is only achieved with all the knobs at full scale and on the last step of the binary count.  Instead of using the scope, there is a volt meter plugin by ML Modules that will show you the actual voltages. I was seeing maximum 0.09 volts with your patch.

**Comment by AdamVerspaget** [comment]
![image](https://user-images.githubusercontent.com/49931541/59062674-c2e42580-88e9-11e9-9d42-5e4d62e0aec6.png)

**Comment by fractalgee** [comment]
aha, thanks, Looks like I misinterpreted what that switch does, my bad, count me educated :)
