### ISSUE TITLE
Sequencer UIs / poss. better to replace 3-position switches with indiv. toggles per out?

### ISSUE THREAD

**Issue by vogelscheiss** [countmodula/VCVRackPlugins#47]
<img width="656" alt="Screen Shot 2020-03-02 at 1 42 25 PM" src="https://user-images.githubusercontent.com/38222883/75706757-bbd92080-5c8b-11ea-90a2-459911865a50.png">
While faithful to the UI of a Doepfer or Analogue Systems sequencer, I'm finding the 3-position toggle switches (as seen in 16-step trigger seq, dual 8-step seq, etc.) unnecessarily cumbersome to use.

An analog switch can be flipped up or down at will, but the code version requires cycling through the possible settings one-by-one. Honestly it can be fiddly and a chore.

Instead my suggestion for what it's worth would be individual on/off toggles for the two possible destinations, per what you'd find on the VCV Pulse Matrix, but much smaller.

This would also eliminate cycling through options, and having to choose between destinations A, B, or none, allowing a 4th option A+B as well.

Just throwing that out there. I love what you're doing.

**Comment by AdamVerspaget** [comment]
Hi, thank you for the suggestion. I can't really change the 3 position switches to two 2 position ones as I would need to expand the panel to nearly double the width to fit them in (making them smaller is not really an option) and it poses a bit of a problem with loading older patches. I have been thinking about the clunky nature of the toggle switches though and am happy to let you know that in version 1.9.0, all toggle switches within the Count Modula suite will operate with click-drags rather than clicks. Click theh switch and drag up to move the batten up, down to move it down. I think this will make all of the modules with toggle switches much easier to use as it is a much more natural way for these to work.

**Comment by vogelscheiss** [comment]
Fair enough, sounds good! One other suggestion, then, if you're retaining the toggles, would be to give them a more obvious differentiation so that it's visually more striking at a glance when they're in the up position vs. the down. What form that would take, I don't know, but it would make it easier to read what's going on at a glance.

For instance, in the attached images switches 2 & 7 are raised but that fact doesn't exactly hit you over the head, it takes a sec to register. Anything that made it more crystal clear would be a plus.

Thanks!

<img width="210" alt="Screen Shot 2020-03-11 at 12 23 46 PM" src="https://user-images.githubusercontent.com/38222883/76439777-4825ca80-6393-11ea-89ac-39c7e8e3ec0c.png">
<img width="213" alt="Screen Shot 2020-03-11 at 12 23 29 PM" src="https://user-images.githubusercontent.com/38222883/76439779-48be6100-6393-11ea-9f24-b496adaba5d0.png">

**Comment by AdamVerspaget** [comment]
Looks like this was not a very popular change, particularly with Andrew. As such I'm afraid I won't be able to make the above UI changes. I am now also reluctant to change the switch graphics.  I have raised a feature request to have the toggle switch behaviour changed to a more user friendly mechanism at a more global level. We'll just have to wait and see how that goes.
