### ISSUE TITLE
G2T module is not triggering below 2.01 volts on Win

### ISSUE THREAD

**Issue by subtleshift** [countmodula/VCVRackPlugins#5]
Tested in a larger patch and with a simple sine wave, G2T isn't giving a gate on 'gate out' or 'inverted' until the signal rises above 2V.  Oddly, it will hold the gate high until it falls to 0.1V.

This is on VCV Rack 0.62 on Windows 10.
Thanks, love the modules!

[G2Tbug.vcv.zip](https://github.com/countmodula/VCVRackPlugins/files/3263491/G2Tbug.vcv.zip)

**Comment by AdamVerspaget** [comment]
Hi, subtleshift, I'm glad you are enjoying the modules.

Those thresholds are by design as the VCV Rack voltage standards outlined [here](https://vcvrack.com/manual/VoltageStandards.html ) dictate a high being a voltage > 2  and a low being voltage < 0.1. The reason for the difference is so that a signal that hovers around either of the thresholds doesn't cause multiple false triggers. This is called hysteresis and the technique is used in most real world modular synths for the same purpose. 

Hope this helps.  Adam.
