### ISSUE TITLE
Input expander for Hyper Maniacal LFO (enhancement)

### ISSUE THREAD

**Issue by danhphotos** [countmodula/VCVRackPlugins#56]
Excellent complex LFO, and the output expander is quite useful. 

This module really begs for an Input expander, to add CV inputs for all parameters of each of the 6 waves (Rate, Range & Waveshape). CV inputs for global Glide & Shape would be great also.

Also, I believe that Level output controls (& CV inputs via an input expander) to allow mixing amounts from each of the 6 waves would turn this into a powerhouse modulator!

Thanks!

**Comment by AdamVerspaget** [comment]
Thank you for the suggestions.  It is kind of getting away from the tribute to the CGS Super Psycho LFO it I intended this to be but an expander to realise these functions is certainly possible.

**Comment by AdamVerspaget** [comment]
Potentially available in v1.12.0.

It probably be called Megalomaniac and when placed to the immediate left of the HMLFO, gives CV over rate, range and waveform for each oscillator along with Manual or CV control over the mix levels of each. Connecting a cable to the range/wave inputs disconnects the associated switch on the HMLFO. Waveforms on the output expander remain unchanged. No CV over the glide section due to the already huge amount of real estate this takes up but that can be added with any of the existing slew limiters (Befaco, Bogaudio etc).

This is what it will probably look like:
![image](https://user-images.githubusercontent.com/49931541/87934854-4a332f00-cad3-11ea-8f4a-8fc9448633d3.png)

**Comment by danhphotos** [comment]
Looks great, thanks!

    On Monday, July 20, 2020, 5:12:12 AM PDT, AdamVerspaget <notifications@github.com> wrote:  
 
 


Potentially available in v1.12.0.

It probably be called Megalomaniac and when placed to the immediate left of the HMLFO, gives CV over rate, range and waveform for each oscillator along with Manual or CV control over the mix levels of each. Connecting a cable to the range/wave inputs disconnects the associated switch on the HMLFO. Waveforms on the output expander remain unchanged. No CV over the glide section due to the already huge amount of real estate this takes up but that can be added with any of the existing slew limiters (Befaco, Bogaudio etc).

This is what it will probably look like:

**Comment by espenstoro** [comment]
Came here to suggest inputs for some feedback insanity options. All taken care of then.  Carry on. :D

**Comment by AdamVerspaget** [comment]
Released in 1.12.0

**Comment by AdamVerspaget** [comment]
Thank you.
