### ISSUE TITLE
D-type Flip-Flop with Preset and Clear

### ISSUE THREAD

**Issue by jpnielsen** [countmodula/VCVRackPlugins#76]
Hi,

I was trying to daisy-chain some seq-3's , and was looing for some type D flip-flops to make a one-hot ring counter.

I couldn't find any modules that have a preset and reset - for this:
https://en.wikipedia.org/wiki/File:Overbeck_Counter_4bit.svg

from [wikipedia](https://en.wikipedia.org/wiki/Ring_counter)

I'm thinking that it must be possible, using you modules - but the solution evades me.

Thanks for making the modules available.

**Comment by AdamVerspaget** [comment]
Hi,

Since the D type flip flops don't have set or reset inputs, it won't be possible with them but perhaps have a look at the CD4022 or CD4017 from the Lunetta Modula plugin. They essentially do what you are looking for without the need to connect multiple flip-flops together.  To limit the count, OR the reset input with the the output AFTER the last one you want and it should perform the ring count you are looking for.
